/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csr_modulo_notas;

import Vista.Pagina_principal;
import java.awt.HeadlessException;
import java.io.InputStream;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author adriana
 */
public class Imprimir_listados extends javax.swing.JFrame {

    /**
     * Creates new form Imprimir_listados
     */
   
    public Imprimir_listados() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("IMPRIMIR LISTADOS");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jClista = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jCGrado = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCAno = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jPanel1.setBackground(java.awt.Color.white);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 781, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "IMPRIMIR LISTADOS", 0, 0, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(1, 0, 255))); // NOI18N

        jLabel1.setText("SELECCIONE TIPO DE LISTA:");

        jButton1.setBackground(java.awt.Color.lightGray);
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Printer.png"))); // NOI18N
        jButton1.setText("IMPRIMIR LISTA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jClista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LISTADO COORDINACION", "LISTADO PAGADURIA", "LISTADO POR CURSO", "LISTADO RECTORIA", "LISTADO  SECRETARIA" }));

        jLabel2.setText("SELECCIONE GRADO:");

        jCGrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PARVULO", "GRADO A", "GRADO B", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11" }));
        jCGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCGradoActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/9898.png"))); // NOI18N

        jLabel4.setText("SELECCIONE AÑO:");

        jCAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2024", "2025", "2026", "2027" }));
        jCAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCAnoActionPerformed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/home-icon.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCGrado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(13, 13, 13))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(12, 12, 12)
                                            .addComponent(jCAno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jClista, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jClista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3)))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", 0, 0, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(0, 26, 255))); // NOI18N

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/png/32x32/promotion.png"))); // NOI18N
        jMenu1.setText("Opciones");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/png/32x32/delete.png"))); // NOI18N
        jMenuItem1.setText("Cerrar Sesión");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCGradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCGradoActionPerformed

    private void jCAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCAnoActionPerformed
     
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         // TODO add your handling code here:
        String logotipo="/Reportes_Primero/logo.jpg";
        conexion cc=new conexion();
        Connection cn=cc.getConnection();
          if(jClista.getSelectedItem().equals("LISTADO RECTORIA")){
          try {
              
              //Insertar logotipo en reporte
                       
              Map parametros=new HashMap();
              parametros.put("Ano",jCAno.getSelectedItem().toString());
              parametros.put("Grado",jCGrado.getSelectedItem().toString());
              parametros.put("logo",this.getClass().getResourceAsStream(logotipo));
              InputStream file= getClass().getResourceAsStream("/Reportes/Rectoria.jrxml");
              JasperDesign jasperDesign= JRXmlLoader.load(file);
              JasperReport jasperReport= JasperCompileManager.compileReport(jasperDesign);
              JasperPrint jp =JasperFillManager.fillReport(jasperReport,parametros,cn);
             JasperViewer ventanaVisor= new JasperViewer(jp,false);
             ventanaVisor.setTitle("RECTORIA");
             ventanaVisor.setVisible(true);
              
              
  
         }
         catch (Exception e) {
             JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);
             System.out.println(e);
         } 
     }else if(jClista.getSelectedItem().equals("LISTADO PAGADURIA")){
         try {
             
             Map parametros=new HashMap();
             Map parametro=new HashMap();
             parametros.put("Ano",jCAno.getSelectedItem().toString());
             parametros.put("Grado",jCGrado.getSelectedItem().toString());
              parametros.put("logo",this.getClass().getResourceAsStream(logotipo));
              InputStream file= getClass().getResourceAsStream("/Reportes/Pagaduria.jrxml");
              JasperDesign jasperDesign= JRXmlLoader.load(file);
              JasperReport jasperReport= JasperCompileManager.compileReport(jasperDesign);
              JasperPrint jp =JasperFillManager.fillReport(jasperReport,parametros,cn);
              JasperViewer ventanaVisor= new JasperViewer(jp,false);
              ventanaVisor.setTitle("LISTADO PAGADURIA");
              ventanaVisor.setVisible(true);
              ventanaVisor.show();
         }
         catch (Exception e) {
             JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);
             
         }
     }else if(jClista.getSelectedItem().equals("LISTADO COORDINACION")){
         try {
            
             Map parametros=new HashMap();
             Map parametro=new HashMap();
             parametros.put("Ano",jCAno.getSelectedItem().toString());
             parametros.put("Grado",jCGrado.getSelectedItem().toString());
             parametros.put("logo",this.getClass().getResourceAsStream(logotipo));
            InputStream file= getClass().getResourceAsStream("/Reportes/Coordi.jrxml");
              JasperDesign jasperDesign= JRXmlLoader.load(file);
              JasperReport jasperReport= JasperCompileManager.compileReport(jasperDesign);
              JasperPrint jp =JasperFillManager.fillReport(jasperReport,parametros,cn);
             JasperViewer ventanaVisor= new JasperViewer(jp,false);
             ventanaVisor.setTitle("LISTADO COORDINACIÓN");
             ventanaVisor.setVisible(true);
         }
         catch (Exception e) {
             JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE"+e,"ERROR",JOptionPane.ERROR_MESSAGE);
             
         } 
           
     }else if(jClista.getSelectedItem().equals("LISTADO  SECRETARIA")){
         try {
             //String rutaInforme="Reportes/Secre.jasper";
             Map parametros=new HashMap();
             Map parametro=new HashMap();
             parametros.put("Ano",jCAno.getSelectedItem().toString());
             parametros.put("Grado",jCGrado.getSelectedItem().toString());
             parametros.put("logo",this.getClass().getResourceAsStream(logotipo));
             InputStream file= getClass().getResourceAsStream("/Reportes/Secre.jrxml");
             JasperDesign jasperDesign= JRXmlLoader.load(file);
             JasperReport jasperReport= JasperCompileManager.compileReport(jasperDesign);
             JasperPrint jp =JasperFillManager.fillReport(jasperReport,parametros,cn);
             JasperViewer ventanaVisor= new JasperViewer(jp,false);
             ventanaVisor.setTitle("LISTADO POR SECRETARIA");
             ventanaVisor.setVisible(true);
         }
         catch (Exception e) {
             JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);
             
         } 
                 } else if(jClista.getSelectedItem().equals("LISTADO POR CURSO")){
         try {
            // String rutaInforme="Reportes/Curso.jasper";
             Map parametros=new HashMap();
             Map parametro=new HashMap();
             parametros.put("Ano",jCAno.getSelectedItem().toString());
             parametros.put("Grado",jCGrado.getSelectedItem().toString());
             parametros.put("logo",this.getClass().getResourceAsStream(logotipo));
             InputStream file= getClass().getResourceAsStream("/Reportes/Grado.jrxml");
             JasperDesign jasperDesign= JRXmlLoader.load(file);
             JasperReport jasperReport= JasperCompileManager.compileReport(jasperDesign);
             JasperPrint jp =JasperFillManager.fillReport(jasperReport,parametros,cn);
             JasperViewer ventanaVisor= new JasperViewer(jp,false);
             ventanaVisor.setTitle("LISTADO POR GRADO");
             ventanaVisor.setVisible(true);
         }
         catch (Exception e) {
             JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);
             
         } 
                 } 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        Pagina_principal inicio=new Pagina_principal();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         int confirmar = JOptionPane.showConfirmDialog(null, "¿Seguro que desea salir del sistema?");
        if(JOptionPane.OK_OPTION==confirmar) {

            try{
                System.exit(0);
            } catch (Exception e){
            }
        }else{
            this.setVisible(true);
                    }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCAno;
    private javax.swing.JComboBox<String> jCGrado;
    private javax.swing.JComboBox<String> jClista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
