/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csr_modulo_notas;

import Vista.Pagina_principal;
import com.toedter.calendar.JYearChooser;
import csr_modulo_notas.conexion;
import java.io.InputStream;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author adriana
 */
public class Seleccion_periodo_1 extends javax.swing.JFrame {

    /**
     * Creates new form Imprimir_listados
     */
    public Seleccion_periodo_1() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("SELECCIÓN PERÍODO");
         Libro_final n = new Libro_final();
         n.setVisible(true);
    }
    
          
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jCGrado = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jCPeriodo = new javax.swing.JComboBox<>();
        jCAno = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jPanel1.setBackground(java.awt.Color.white);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 781, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GESTIONAR NOTAS ", 0, 0, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(1, 0, 255))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/9898.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/home-icon.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        jPanel3.setBackground(java.awt.Color.white);
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SELECCIONE LOS CAMPOS CORRESPONDIENTES", 0, 0, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(111, 161, 244))); // NOI18N

        jCGrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11" }));
        jCGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCGradoActionPerformed(evt);
            }
        });

        jLabel2.setText("SELECCIONE GRADO");

        jLabel1.setText("SELECCIONE EL PERÍODO A DIGITAR:");

        jCPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PRIMERO", "SEGUNDO", "TERCERO", "CUARTO" }));

        jCAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029" }));
        jCAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCAnoActionPerformed(evt);
            }
        });

        jLabel4.setText("SELECCIONE EL AÑO PARA DIGITAR:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(174, 174, 174)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(38, 38, 38)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jCGrado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCPeriodo, 0, 195, Short.MAX_VALUE)
                        .addComponent(jCAno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(174, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(11, 11, 11)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel4.setBackground(java.awt.Color.white);
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INFORMES DE COORDINACIÓN", 0, 0, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(140, 162, 225))); // NOI18N

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/png/48x48/chart_pie.png"))); // NOI18N
        jButton4.setText("CONSOLIDADO DE NOTAS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/png/48x48/new_page.png"))); // NOI18N
        jButton2.setText("CONSOLIDADO DE PROMEDIOS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(133, 133, 133))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel5.setBackground(java.awt.Color.white);
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NOTAS Y BOLETINES", 0, 0, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(140, 162, 225))); // NOI18N

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/png/48x48/chart.png"))); // NOI18N
        jButton3.setText("IMPRIMIR INFORMES");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Forward.png"))); // NOI18N
        jButton1.setText("DIGITAR NOTAS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6)
                        .addGap(0, 231, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", 0, 0, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(0, 26, 255))); // NOI18N

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/png/32x32/promotion.png"))); // NOI18N
        jMenu1.setText("Opciones");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/png/32x32/delete.png"))); // NOI18N
        jMenuItem1.setText("Cerrar sesión");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 870, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCGradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCGradoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         
                Libro_final.jAno.setText(jCAno.getSelectedItem().toString());
                Libro_final.jGrado.setText(jCGrado.getSelectedItem().toString());
                Libro_final.jPeriodo.setText(jCPeriodo.getSelectedItem().toString());
                this.setVisible(false);
                 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        Pagina_principal inicio = new Pagina_principal();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        int confirmar = JOptionPane.showConfirmDialog(null, "¿Seguro que desea salir del sistema?");
        if (JOptionPane.OK_OPTION == confirmar) {

            try {
                System.exit(0);
            } catch (Exception e) {
            }
        } else {
            this.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jCAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCAnoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        String logotipo="/Reportes_Primero/logo.jpg";
        conexion cc=new conexion();
        Connection cn=cc.getConnection();
     if(jCPeriodo.getSelectedItem().equals("PRIMERO") ){
         if(jCGrado.getSelectedItem().equals("3") || jCGrado .getSelectedItem().equals("4") || jCGrado.getSelectedItem().equals("5")){
         
         try {
             
             Map parametros=new HashMap();
             parametros.put("Ano",jCAno.getSelectedItem().toString());
             parametros.put("Grado",jCGrado.getSelectedItem().toString());
             parametros.put("logo",this.getClass().getResourceAsStream(logotipo));
             parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
             InputStream file= getClass().getResourceAsStream("/Reportes_Primero/Primaria.jrxml");
             JasperDesign jasperDesign= JRXmlLoader.load(file);
             JasperReport jasperReport= JasperCompileManager.compileReport(jasperDesign);
             JasperPrint jp =JasperFillManager.fillReport(jasperReport,parametros,cn);
             JasperViewer ventanaVisor= new JasperViewer(jp,false);
             ventanaVisor.setTitle("INFORME PRIMER PERÍODO");
             ventanaVisor.setVisible(true);
             
             
      
         }
         catch (Exception e) {
             JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);
             
         } 
        }
         else if(jCPeriodo.getSelectedItem().equals("PRIMERO") ){
         if(jCGrado.getSelectedItem().equals("1") || jCGrado .getSelectedItem().equals("2") || jCGrado.getSelectedItem().equals("3") || jCGrado.getSelectedItem().equals("4") || jCGrado.getSelectedItem().equals("5") ){
         
         try {
             
             Map parametros=new HashMap();
             parametros.put("Ano",jCAno.getSelectedItem().toString());
             parametros.put("Grado",jCGrado.getSelectedItem().toString());
             parametros.put("logo",this.getClass().getResourceAsStream(logotipo));
             parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
             InputStream file= getClass().getResourceAsStream("/Reportes_Primero/Primaria_uno_dos.jrxml");
             JasperDesign jasperDesign= JRXmlLoader.load(file);
             JasperReport jasperReport= JasperCompileManager.compileReport(jasperDesign);
             JasperPrint jp =JasperFillManager.fillReport(jasperReport,parametros,cn);
             JasperViewer ventanaVisor= new JasperViewer(jp,false);
             ventanaVisor.setTitle("INFORME PRIMER PERÍODO");
             ventanaVisor.setVisible(true);
             
             
      
         }
         catch (Exception e) {
             JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);
             
         } 
        }

         else if(jCGrado.getSelectedItem().equals("6") || jCGrado.getSelectedItem().equals("7") || jCGrado.getSelectedItem().equals("8")){
         
         try {
             Map parametros=new HashMap();
             parametros.put("Ano",jCAno.getSelectedItem().toString());
             parametros.put("Grado",jCGrado.getSelectedItem().toString());
             parametros.put("logo",this.getClass().getResourceAsStream(logotipo));
             parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
             InputStream file= getClass().getResourceAsStream("/Reportes_Primero/Secundaria.jrxml");
             JasperDesign jasperDesign= JRXmlLoader.load(file);
             JasperReport jasperReport= JasperCompileManager.compileReport(jasperDesign);
             JasperPrint jp =JasperFillManager.fillReport(jasperReport,parametros,cn);
             JasperViewer ventanaVisor= new JasperViewer(jp,false);
             ventanaVisor.setTitle("INFORME PRIMER PERÍODO");
             ventanaVisor.setVisible(true);
             
         }
         catch (Exception e) {
             JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);
             
         } 
     }//END IF SEXTO
        else if(jCGrado.getSelectedItem().equals("9")){
         
         try {
             Map parametros=new HashMap();
             parametros.put("Ano",jCAno.getSelectedItem().toString());
             parametros.put("Grado",jCGrado.getSelectedItem().toString());
             parametros.put("logo",this.getClass().getResourceAsStream(logotipo));
             parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
             InputStream file= getClass().getResourceAsStream("/Reportes_Primero/Media.jrxml");
             JasperDesign jasperDesign= JRXmlLoader.load(file);
             JasperReport jasperReport= JasperCompileManager.compileReport(jasperDesign);
             JasperPrint jp =JasperFillManager.fillReport(jasperReport,parametros,cn);
             JasperViewer ventanaVisor= new JasperViewer(jp,false);
             ventanaVisor.setTitle("INFORME PRIMER PERÍODO");
             ventanaVisor.setVisible(true);
             
         }
         catch (Exception e) {
             JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);
             
         } 
     }else if(jCGrado.getSelectedItem().equals("10") || jCGrado.getSelectedItem().equals("11")){
         
         try {
             Map parametros=new HashMap();
             parametros.put("Ano",jCAno.getSelectedItem().toString());
             parametros.put("Grado",jCGrado.getSelectedItem().toString());
             parametros.put("logo",this.getClass().getResourceAsStream(logotipo));
             parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
             InputStream file= getClass().getResourceAsStream("/Reportes_Primero/Once.jrxml");
             JasperDesign jasperDesign= JRXmlLoader.load(file);
             JasperReport jasperReport= JasperCompileManager.compileReport(jasperDesign);
             JasperPrint jp =JasperFillManager.fillReport(jasperReport,parametros,cn);
             JasperViewer ventanaVisor= new JasperViewer(jp,false);
             ventanaVisor.setTitle("INFORME PRIMER PERÍODO");
             ventanaVisor.setVisible(true);
             
         }
         catch (Exception e) {
             JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);
             
         } 
     } 
     }
          
   //// INICIO SEGUNDO PERIODO       
     else if(jCPeriodo.getSelectedItem().equals("SEGUNDO") ){
         if(jCGrado.getSelectedItem().equals("1") || jCGrado.getSelectedItem().equals("2") || jCGrado.getSelectedItem().equals("3") || jCGrado.getSelectedItem().equals("4") || jCGrado.getSelectedItem().equals("5") ){
         
         try {
             String rutaInforme="Reportes_Segundo/Primaria.jasper";
             Map parametros=new HashMap();
             Map parametro=new HashMap();
             parametros.put("Ano",jCAno.getSelectedItem().toString());
             parametros.put("Grado",jCGrado.getSelectedItem().toString());
             parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
             JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
             JasperViewer ventanaVisor= new JasperViewer(Informe,false);
             ventanaVisor.setTitle("INFORME ACADÉMICO SEGUNDO PERIODO");
             ventanaVisor.setVisible(true);
         }
         catch (Exception e) {
             JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);
             
         } 
        }
         
         else if(jCGrado.getSelectedItem().equals("6") || jCGrado.getSelectedItem().equals("7") || jCGrado.getSelectedItem().equals("8")){
         
         try {
            String rutaInforme="Reportes_Segundo/Secundaria.jasper";
             Map parametros=new HashMap();
             Map parametro=new HashMap();
             parametros.put("Ano",jCAno.getSelectedItem().toString());
             parametros.put("Grado",jCGrado.getSelectedItem().toString());
             parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
             JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
             JasperViewer ventanaVisor= new JasperViewer(Informe,false);
             ventanaVisor.setTitle("INFORME ACADÉMICO SEGUNDO PERIODO");
             ventanaVisor.setVisible(true);
         }
         catch (Exception e) {
             JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);
             
         } 
     }//END IF SEXTO
        else if(jCGrado.getSelectedItem().equals("9")){
         
         try {
            String rutaInforme="Reportes_Segundo/Media.jasper";
             Map parametros=new HashMap();
             Map parametro=new HashMap();
             parametros.put("Ano",jCAno.getSelectedItem().toString());
             parametros.put("Grado",jCGrado.getSelectedItem().toString());
             parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
             JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
             JasperViewer ventanaVisor= new JasperViewer(Informe,false);
             ventanaVisor.setTitle("INFORME ACADÉMICO SEGUNDO PERIODO");
             ventanaVisor.setVisible(true);
         }
         catch (Exception e) {
             JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);
             
         } 
     }else if(jCGrado.getSelectedItem().equals("10") || jCGrado.getSelectedItem().equals("11")){
         
         try {
            String rutaInforme="Reportes_Segundo/Once.jasper";
             Map parametros=new HashMap();
             Map parametro=new HashMap();
             parametros.put("Ano",jCAno.getSelectedItem().toString());
             parametros.put("Grado",jCGrado.getSelectedItem().toString());
             parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
             JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
             JasperViewer ventanaVisor= new JasperViewer(Informe,false);
             ventanaVisor.setTitle("INFORME ACADÉMICO SEGUNDO PERIODO");
             ventanaVisor.setVisible(true);
         }
         catch (Exception e) {
             JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);
             
         } 
     }
     }
/////////////////////////////////////// INICIO TERCER PERÍODO////////////////////////////////
 else if(jCPeriodo.getSelectedItem().equals("TERCERO") ){
         if(jCGrado.getSelectedItem().equals("1") || jCGrado.getSelectedItem().equals("2")){
         
         try {
             String rutaInforme="Reportes_Tercero/Primaria_uno_dos.jasper";
             Map parametros=new HashMap();
             Map parametro=new HashMap();
             parametros.put("Ano",jCAno.getSelectedItem().toString());
             parametros.put("Grado",jCGrado.getSelectedItem().toString());
             parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
             JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
             JasperViewer ventanaVisor= new JasperViewer(Informe,false);
             ventanaVisor.setTitle("INFORME ACADÉMICO TERCER PERIODO");
             ventanaVisor.setVisible(true);
         }
         catch (Exception e) {
             JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);
             
         } 
        }
          if(jCGrado.getSelectedItem().equals("3") || jCGrado.getSelectedItem().equals("4") || jCGrado.getSelectedItem().equals("5") ){
         
         try {
             String rutaInforme="Reportes_Tercero/Primaria.jasper";
             Map parametros=new HashMap();
             Map parametro=new HashMap();
             parametros.put("Ano",jCAno.getSelectedItem().toString());
             parametros.put("Grado",jCGrado.getSelectedItem().toString());
             parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
             JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
             JasperViewer ventanaVisor= new JasperViewer(Informe,false);
             ventanaVisor.setTitle("INFORME ACADÉMICO TERCER PERIODO");
             ventanaVisor.setVisible(true);
         }
         catch (Exception e) {
             JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);
             
         } 
        }
         
     
         
         else if(jCGrado.getSelectedItem().equals("6") || jCGrado.getSelectedItem().equals("7") || jCGrado.getSelectedItem().equals("8")){
         
         try {
            String rutaInforme="Reportes_Tercero/Secundaria.jasper";
             Map parametros=new HashMap();
             Map parametro=new HashMap();
             parametros.put("Ano",jCAno.getSelectedItem().toString());
             parametros.put("Grado",jCGrado.getSelectedItem().toString());
             parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
             JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
             JasperViewer ventanaVisor= new JasperViewer(Informe,false);
             ventanaVisor.setTitle("INFORME ACADÉMICO TERCER PERIODO");
             ventanaVisor.setVisible(true);
         }
         catch (Exception e) {
             JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);
             
         } 
     }//END IF SEXTO
        else if(jCGrado.getSelectedItem().equals("9")){
         
         try {
            String rutaInforme="Reportes_Tercero/Media.jasper";
             Map parametros=new HashMap();
             Map parametro=new HashMap();
             parametros.put("Ano",jCAno.getSelectedItem().toString());
             parametros.put("Grado",jCGrado.getSelectedItem().toString());
             parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
             JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
             JasperViewer ventanaVisor= new JasperViewer(Informe,false);
             ventanaVisor.setTitle("INFORME ACADÉMICO TERCER PERIODO");
             ventanaVisor.setVisible(true);
         }
         catch (Exception e) {
             JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);
             
         } 
     }else if(jCGrado.getSelectedItem().equals("10") || jCGrado.getSelectedItem().equals("11")){
         
         try {
            String rutaInforme="Reportes_Tercero/Once.jasper";
             Map parametros=new HashMap();
             Map parametro=new HashMap();
             parametros.put("Ano",jCAno.getSelectedItem().toString());
             parametros.put("Grado",jCGrado.getSelectedItem().toString());
             parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
             JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
             JasperViewer ventanaVisor= new JasperViewer(Informe,false);
             ventanaVisor.setTitle("INFORME ACADÉMICO TERCER PERIODO");
             ventanaVisor.setVisible(true);
         }
         catch (Exception e) {
             JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);
             
         } 
     }
     }
     
     /////////////////////////////////////// INICIO CUARTO   PERÍODO////////////////////////////////
 else if(jCPeriodo.getSelectedItem().equals("CUARTO") ){
         if(jCGrado.getSelectedItem().equals("1") || jCGrado.getSelectedItem().equals("2")){
         
         try {
             String rutaInforme="Reportes_Cuarto/Primaria_uno_dos.jasper";
             Map parametros=new HashMap();
             Map parametro=new HashMap();
             parametros.put("Ano",jCAno.getSelectedItem().toString());
             parametros.put("Grado",jCGrado.getSelectedItem().toString());
             parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
             JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
             JasperViewer ventanaVisor= new JasperViewer(Informe,false);
             ventanaVisor.setTitle("INFORME ACADÉMICO CUARTO PERIODO");
             ventanaVisor.setVisible(true);
         }
         catch (Exception e) {
             JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);
             
         } 
        }
          if(jCGrado.getSelectedItem().equals("3") || jCGrado.getSelectedItem().equals("4") || jCGrado.getSelectedItem().equals("5") ){
         
         try {
             String rutaInforme="Reportes_Cuarto/Primaria.jasper";
             Map parametros=new HashMap();
             Map parametro=new HashMap();
             parametros.put("Ano",jCAno.getSelectedItem().toString());
             parametros.put("Grado",jCGrado.getSelectedItem().toString());
             parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
             JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
             JasperViewer ventanaVisor= new JasperViewer(Informe,false);
             ventanaVisor.setTitle("INFORME ACADÉMICO CUARTO PERIODO");
             ventanaVisor.setVisible(true);
         }
         catch (Exception e) {
             JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);
             
         } 
        }
         
     
         
         else if(jCGrado.getSelectedItem().equals("6") || jCGrado.getSelectedItem().equals("7") || jCGrado.getSelectedItem().equals("8")){
         
         try {
            String rutaInforme="Reportes_Cuarto/Secundaria.jasper";
             Map parametros=new HashMap();
             Map parametro=new HashMap();
             parametros.put("Ano",jCAno.getSelectedItem().toString());
             parametros.put("Grado",jCGrado.getSelectedItem().toString());
             parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
             JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
             JasperViewer ventanaVisor= new JasperViewer(Informe,false);
             ventanaVisor.setTitle("INFORME ACADÉMICO CUARTO PERIODO");
             ventanaVisor.setVisible(true);
         }
         catch (Exception e) {
             JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);
             
         } 
     }//END IF SEXTO
        else if(jCGrado.getSelectedItem().equals("9")){
         
         try {
            String rutaInforme="Reportes_Cuarto/Media.jasper";
             Map parametros=new HashMap();
             Map parametro=new HashMap();
             parametros.put("Ano",jCAno.getSelectedItem().toString());
             parametros.put("Grado",jCGrado.getSelectedItem().toString());
             parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
             JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
             JasperViewer ventanaVisor= new JasperViewer(Informe,false);
             ventanaVisor.setTitle("INFORME ACADÉMICO CUARTO PERIODO");
             ventanaVisor.setVisible(true);
         }
         catch (Exception e) {
             JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);
             
         } 
     }else if(jCGrado.getSelectedItem().equals("10") || jCGrado.getSelectedItem().equals("11")){
         
         try {
            String rutaInforme="Reportes_Cuarto/Once.jasper";
             Map parametros=new HashMap();
             Map parametro=new HashMap();
             parametros.put("Ano",jCAno.getSelectedItem().toString());
             parametros.put("Grado",jCGrado.getSelectedItem().toString());
             parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
             JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
             JasperViewer ventanaVisor= new JasperViewer(Informe,false);
             ventanaVisor.setTitle("INFORME ACADÉMICO CUARTO PERIODO");
             ventanaVisor.setVisible(true);
         }
         catch (Exception e) {
             JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);
             
         } 
     }
     }
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     }     
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String logotipo="/Reportes_Primero/logo.jpg";
        conexion cc=new conexion();
        Connection cn=cc.getConnection();
        if(jCPeriodo.getSelectedItem().equals("PRIMERO") ){
            if(jCGrado.getSelectedItem().equals("1") || jCGrado.getSelectedItem().equals("2") || jCGrado.getSelectedItem().equals("3") || jCGrado.getSelectedItem().equals("4") || jCGrado.getSelectedItem().equals("5") ){

                try {
             Map parametros=new HashMap();
             parametros.put("Ano",jCAno.getSelectedItem().toString());
             parametros.put("Grado",jCGrado.getSelectedItem().toString());
             parametros.put("logo",this.getClass().getResourceAsStream(logotipo));
             parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
             InputStream file= getClass().getResourceAsStream("/Reportes_Primero/Consolidado_Primaria_uno_dos.jrxml");
             JasperDesign jasperDesign= JRXmlLoader.load(file);
             JasperReport jasperReport= JasperCompileManager.compileReport(jasperDesign);
             JasperPrint jp =JasperFillManager.fillReport(jasperReport,parametros,cn);
             JasperViewer ventanaVisor= new JasperViewer(jp,false);
             ventanaVisor.setTitle("INFORME PRIMER PERÍODO");
             ventanaVisor.setVisible(true);
             
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            }
            
           
           
            else if(jCPeriodo.getSelectedItem().equals("PRIMERO") ){
             if(jCGrado.getSelectedItem().equals("1") || jCGrado .getSelectedItem().equals("2") || jCGrado.getSelectedItem().equals("3") || jCGrado.getSelectedItem().equals("4") || jCGrado.getSelectedItem().equals("5") ){
         
            try {
             
             Map parametros=new HashMap();
             parametros.put("Ano",jCAno.getSelectedItem().toString());
             parametros.put("Grado",jCGrado.getSelectedItem().toString());
             parametros.put("logo",this.getClass().getResourceAsStream(logotipo));
             parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
             InputStream file= getClass().getResourceAsStream("/Reportes_Primero/Consolidado_Primaria.jrxml");
             JasperDesign jasperDesign= JRXmlLoader.load(file);
             JasperReport jasperReport= JasperCompileManager.compileReport(jasperDesign);
             JasperPrint jp =JasperFillManager.fillReport(jasperReport,parametros,cn);
             JasperViewer ventanaVisor= new JasperViewer(jp,false);
             ventanaVisor.setTitle("INFORME PRIMER PERÍODO");
             ventanaVisor.setVisible(true);
             
             
      
         }
         catch (Exception e) {
             JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);
             
         } 
        }

            
   
            
            
            
            else if(jCGrado.getSelectedItem().equals("6") || jCGrado.getSelectedItem().equals("7") || jCGrado.getSelectedItem().equals("8")){

                try {
                    Map parametros=new HashMap();
                    parametros.put("Ano",jCAno.getSelectedItem().toString());
                    parametros.put("Grado",jCGrado.getSelectedItem().toString());
                    parametros.put("logo",this.getClass().getResourceAsStream(logotipo));
                    parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
                    InputStream file= getClass().getResourceAsStream("/Reportes_Primero/Consolidado_Secundaria.jrxml");
                    JasperDesign jasperDesign= JRXmlLoader.load(file);
                    JasperReport jasperReport= JasperCompileManager.compileReport(jasperDesign);
                    JasperPrint jp =JasperFillManager.fillReport(jasperReport,parametros,cn);
                    JasperViewer ventanaVisor= new JasperViewer(jp,false);
                    ventanaVisor.setTitle("INFORME PRIMER PERÍODO");
                    ventanaVisor.setVisible(true);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            }//END IF SEXTO
            else if(jCGrado.getSelectedItem().equals("9")){

                try {
                    Map parametros=new HashMap();
                    parametros.put("Ano",jCAno.getSelectedItem().toString());
                    parametros.put("Grado",jCGrado.getSelectedItem().toString());
                    parametros.put("logo",this.getClass().getResourceAsStream(logotipo));
                    parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
                    InputStream file= getClass().getResourceAsStream("/Reportes_Primero/Consolidado_Media.jrxml");
                    JasperDesign jasperDesign= JRXmlLoader.load(file);
                    JasperReport jasperReport= JasperCompileManager.compileReport(jasperDesign);
                    JasperPrint jp =JasperFillManager.fillReport(jasperReport,parametros,cn);
                    JasperViewer ventanaVisor= new JasperViewer(jp,false);
                    ventanaVisor.setTitle("INFORME PRIMER PERÍODO");
                    ventanaVisor.setVisible(true);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            }else if(jCGrado.getSelectedItem().equals("10") || jCGrado.getSelectedItem().equals("11")){

                try {
                    Map parametros=new HashMap();
                    parametros.put("Ano",jCAno.getSelectedItem().toString());
                    parametros.put("Grado",jCGrado.getSelectedItem().toString());
                    parametros.put("logo",this.getClass().getResourceAsStream(logotipo));
                    parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
                    InputStream file= getClass().getResourceAsStream("/Reportes_Primero/Conso.jrxml");
                    JasperDesign jasperDesign= JRXmlLoader.load(file);
                    JasperReport jasperReport= JasperCompileManager.compileReport(jasperDesign);
                    JasperPrint jp =JasperFillManager.fillReport(jasperReport,parametros,cn);
                    JasperViewer ventanaVisor= new JasperViewer(jp,false);
                    ventanaVisor.setTitle("INFORME PRIMER PERÍODO");
                    ventanaVisor.setVisible(true);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            }
        }
        else if(jCPeriodo.getSelectedItem().equals("SEGUNDO") ){
            if(jCGrado.getSelectedItem().equals("1") || jCGrado.getSelectedItem().equals("2") || jCGrado.getSelectedItem().equals("3") || jCGrado.getSelectedItem().equals("4") || jCGrado.getSelectedItem().equals("5") ){

                try {
                    String rutaInforme="Reportes_Segundo/Primaria.jasper";
                    Map parametros=new HashMap();
                    Map parametro=new HashMap();
                    parametros.put("Ano",jCAno.getSelectedItem().toString());
                    parametros.put("Grado",jCGrado.getSelectedItem().toString());
                    parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
                    JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
                    JasperViewer ventanaVisor= new JasperViewer(Informe,false);
                    ventanaVisor.setTitle("INFORME ACADÉMICO SEGUNDO PERIODO");
                    ventanaVisor.setVisible(true);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            }

            else if(jCGrado.getSelectedItem().equals("6") || jCGrado.getSelectedItem().equals("7") || jCGrado.getSelectedItem().equals("8")){

                try {
                    String rutaInforme="Reportes_Segundo/Secundaria.jasper";
                    Map parametros=new HashMap();
                    Map parametro=new HashMap();
                    parametros.put("Ano",jCAno.getSelectedItem().toString());
                    parametros.put("Grado",jCGrado.getSelectedItem().toString());
                    parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
                    JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
                    JasperViewer ventanaVisor= new JasperViewer(Informe,false);
                    ventanaVisor.setTitle("INFORME ACADÉMICO SEGUNDO PERIODO");
                    ventanaVisor.setVisible(true);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            }//END IF SEXTO
            else if(jCGrado.getSelectedItem().equals("9")){

                try {
                    String rutaInforme="Reportes_Segundo/Media.jasper";
                    Map parametros=new HashMap();
                    Map parametro=new HashMap();
                    parametros.put("Ano",jCAno.getSelectedItem().toString());
                    parametros.put("Grado",jCGrado.getSelectedItem().toString());
                    parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
                    JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
                    JasperViewer ventanaVisor= new JasperViewer(Informe,false);
                    ventanaVisor.setTitle("INFORME ACADÉMICO TERCER PERIODO");
                    ventanaVisor.setVisible(true);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            }else if(jCGrado.getSelectedItem().equals("10") || jCGrado.getSelectedItem().equals("11")){

                try {
                    String rutaInforme="Reportes_Segundo/Once.jasper";
                    Map parametros=new HashMap();
                    Map parametro=new HashMap();
                    parametros.put("Ano",jCAno.getSelectedItem().toString());
                    parametros.put("Grado",jCGrado.getSelectedItem().toString());
                    parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
                    JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
                    JasperViewer ventanaVisor= new JasperViewer(Informe,false);
                    ventanaVisor.setTitle("INFORME ACADÉMICO SEGUNDO PERIODO");
                    ventanaVisor.setVisible(true);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            }
        }
        /////////////////////////////////////// INICIO TERCER PERÍODO////////////////////////////////
        else if(jCPeriodo.getSelectedItem().equals("TERCERO") ){
            if(jCGrado.getSelectedItem().equals("1") || jCGrado.getSelectedItem().equals("2") ){

                try {
                    String rutaInforme="Reportes_Tercero/Consolidado_Primaria_uno_dos.jasper";
                    Map parametros=new HashMap();
                    Map parametro=new HashMap();
                    parametros.put("Ano",jCAno.getSelectedItem().toString());
                    parametros.put("Grado",jCGrado.getSelectedItem().toString());
                    parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
                    JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
                    JasperViewer ventanaVisor= new JasperViewer(Informe,false);
                    ventanaVisor.setTitle("CONSOLIDADO DE NOTAS TERCER PERIODO");
                    ventanaVisor.setVisible(true);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            }
            
             if(jCGrado.getSelectedItem().equals("3") || jCGrado.getSelectedItem().equals("4") || jCGrado.getSelectedItem().equals("5") ){

                try {
                    String rutaInforme="Reportes_Tercero/Consolidado_Primaria.jasper";
                    Map parametros=new HashMap();
                    Map parametro=new HashMap();
                    parametros.put("Ano",jCAno.getSelectedItem().toString());
                    parametros.put("Grado",jCGrado.getSelectedItem().toString());
                    parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
                    JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
                    JasperViewer ventanaVisor= new JasperViewer(Informe,false);
                    ventanaVisor.setTitle("CONSOLIDADO DE NOTAS TERCER PERIODO");
                    ventanaVisor.setVisible(true);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            }
                   
            
            else if(jCGrado.getSelectedItem().equals("6") || jCGrado.getSelectedItem().equals("7") || jCGrado.getSelectedItem().equals("8")){

                try {
                    String rutaInforme="Reportes_Tercero/Consolidado_Secundaria.jasper";
                    Map parametros=new HashMap();
                    Map parametro=new HashMap();
                    parametros.put("Ano",jCAno.getSelectedItem().toString());
                    parametros.put("Grado",jCGrado.getSelectedItem().toString());
                    parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
                    JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
                    JasperViewer ventanaVisor= new JasperViewer(Informe,false);
                    ventanaVisor.setTitle("CONSOLIDADO DE NOTAS TERCER PERIODO");
                    ventanaVisor.setVisible(true);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            }//END IF SEXTO
            else if(jCGrado.getSelectedItem().equals("9")){

                try {
                    String rutaInforme="Reportes_Tercero/Consolidado_Media.jasper";
                    Map parametros=new HashMap();
                    Map parametro=new HashMap();
                    parametros.put("Ano",jCAno.getSelectedItem().toString());
                    parametros.put("Grado",jCGrado.getSelectedItem().toString());
                    parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
                    JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
                    JasperViewer ventanaVisor= new JasperViewer(Informe,false);
                    ventanaVisor.setTitle("CONSOLIDADO DE NOTAS TERCER PERIODO");
                    ventanaVisor.setVisible(true);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            }else if(jCGrado.getSelectedItem().equals("10") || jCGrado.getSelectedItem().equals("11")){

                try {
                    String rutaInforme="Reportes_Tercero/Consolidado_Once.jasper";
                    Map parametros=new HashMap();
                    Map parametro=new HashMap();
                    parametros.put("Ano",jCAno.getSelectedItem().toString());
                    parametros.put("Grado",jCGrado.getSelectedItem().toString());
                    parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
                    JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
                    JasperViewer ventanaVisor= new JasperViewer(Informe,false);
                    ventanaVisor.setTitle("CONSOLIDADO DE NOTAS TERCER PERIODO");
                    ventanaVisor.setVisible(true);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            }
        }
        
          /////////////////////////////////////// INICIO CUARTO PERÍODO////////////////////////////////
        else if(jCPeriodo.getSelectedItem().equals("CUARTO") ){
            if(jCGrado.getSelectedItem().equals("1") || jCGrado.getSelectedItem().equals("2") ){

                try {
                    String rutaInforme="Reportes_Cuarto/Consolidado_Primaria_uno_dos.jasper";
                    Map parametros=new HashMap();
                    Map parametro=new HashMap();
                    parametros.put("Ano",jCAno.getSelectedItem().toString());
                    parametros.put("Grado",jCGrado.getSelectedItem().toString());
                    parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
                    JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
                    JasperViewer ventanaVisor= new JasperViewer(Informe,false);
                    ventanaVisor.setTitle("CONSOLIDADO DE NOTAS CUARTO PERIODO");
                    ventanaVisor.setVisible(true);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            }
            
             if(jCGrado.getSelectedItem().equals("3") || jCGrado.getSelectedItem().equals("4") || jCGrado.getSelectedItem().equals("5") ){

                try {
                    String rutaInforme="Reportes_Cuarto/Consolidado_Primaria.jasper";
                    Map parametros=new HashMap();
                    Map parametro=new HashMap();
                    parametros.put("Ano",jCAno.getSelectedItem().toString());
                    parametros.put("Grado",jCGrado.getSelectedItem().toString());
                    parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
                    JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
                    JasperViewer ventanaVisor= new JasperViewer(Informe,false);
                    ventanaVisor.setTitle("CONSOLIDADO DE NOTAS CUARTO PERIODO");
                    ventanaVisor.setVisible(true);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            }
                   
            
            else if(jCGrado.getSelectedItem().equals("6") || jCGrado.getSelectedItem().equals("7") || jCGrado.getSelectedItem().equals("8")){

                try {
                    String rutaInforme="Reportes_Cuarto/Consolidado_Secundaria.jasper";
                    Map parametros=new HashMap();
                    Map parametro=new HashMap();
                    parametros.put("Ano",jCAno.getSelectedItem().toString());
                    parametros.put("Grado",jCGrado.getSelectedItem().toString());
                    parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
                    JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
                    JasperViewer ventanaVisor= new JasperViewer(Informe,false);
                    ventanaVisor.setTitle("CONSOLIDADO DE NOTAS CUARTO PERIODO");
                    ventanaVisor.setVisible(true);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            }//END IF SEXTO
            else if(jCGrado.getSelectedItem().equals("9")){

                try {
                    String rutaInforme="Reportes_Cuarto/Consolidado_Media.jasper";
                    Map parametros=new HashMap();
                    Map parametro=new HashMap();
                    parametros.put("Ano",jCAno.getSelectedItem().toString());
                    parametros.put("Grado",jCGrado.getSelectedItem().toString());
                    parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
                    JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
                    JasperViewer ventanaVisor= new JasperViewer(Informe,false);
                    ventanaVisor.setTitle("CONSOLIDADO DE NOTAS  CUARTO PERIODO");
                    ventanaVisor.setVisible(true);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            }else if(jCGrado.getSelectedItem().equals("10") || jCGrado.getSelectedItem().equals("11")){

                try {
                    String rutaInforme="Reportes_Cuarto/Consolidado_Once.jasper";
                    Map parametros=new HashMap();
                    Map parametro=new HashMap();
                    parametros.put("Ano",jCAno.getSelectedItem().toString());
                    parametros.put("Grado",jCGrado.getSelectedItem().toString());
                    parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
                    JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
                    JasperViewer ventanaVisor= new JasperViewer(Informe,false);
                    ventanaVisor.setTitle("CONSOLIDADO DE NOTAS CUARTO PERIODO");
                    ventanaVisor.setVisible(true);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            }
        }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 String logotipo="/Reportes_Primero/logo.jpg";
        conexion cc=new conexion();
        Connection cn=cc.getConnection();
        if(jCPeriodo.getSelectedItem().equals("PRIMERO") ){
            if(jCGrado.getSelectedItem().equals("1") || jCGrado.getSelectedItem().equals("2") || jCGrado.getSelectedItem().equals("3") || jCGrado.getSelectedItem().equals("4") || jCGrado.getSelectedItem().equals("5") ){

                try {
             Map parametros=new HashMap();
             parametros.put("Ano",jCAno.getSelectedItem().toString());
             parametros.put("Grado",jCGrado.getSelectedItem().toString());
             parametros.put("logo",this.getClass().getResourceAsStream(logotipo));
             parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
             InputStream file= getClass().getResourceAsStream("/Reportes_Primero/Promedio_Primaria_uno_dos.jrxml");
             JasperDesign jasperDesign= JRXmlLoader.load(file);
             JasperReport jasperReport= JasperCompileManager.compileReport(jasperDesign);
             JasperPrint jp =JasperFillManager.fillReport(jasperReport,parametros,cn);
             JasperViewer ventanaVisor= new JasperViewer(jp,false);
             ventanaVisor.setTitle("INFORME PROMEDIOS PRIMER PERÍODO");
             ventanaVisor.setVisible(true);
             
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            }
            
           
           
            else if(jCPeriodo.getSelectedItem().equals("PRIMERO") ){
             if(jCGrado.getSelectedItem().equals("1") || jCGrado .getSelectedItem().equals("2") || jCGrado.getSelectedItem().equals("3") || jCGrado.getSelectedItem().equals("4") || jCGrado.getSelectedItem().equals("5") ){
         
            try {
             
             Map parametros=new HashMap();
             parametros.put("Ano",jCAno.getSelectedItem().toString());
             parametros.put("Grado",jCGrado.getSelectedItem().toString());
             parametros.put("logo",this.getClass().getResourceAsStream(logotipo));
             parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
             InputStream file= getClass().getResourceAsStream("/Reportes_Primero/Promedio_Primaria.jrxml");
             JasperDesign jasperDesign= JRXmlLoader.load(file);
             JasperReport jasperReport= JasperCompileManager.compileReport(jasperDesign);
             JasperPrint jp =JasperFillManager.fillReport(jasperReport,parametros,cn);
             JasperViewer ventanaVisor= new JasperViewer(jp,false);
             ventanaVisor.setTitle("INFORME PROMEDIOS PRIMER PERÍODO");
             ventanaVisor.setVisible(true);
             
             
      
         }
         catch (Exception e) {
             JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);
             
         } 
        }

            
   
            
            
            
            else if(jCGrado.getSelectedItem().equals("6") || jCGrado.getSelectedItem().equals("7") || jCGrado.getSelectedItem().equals("8")){

                try {
                    Map parametros=new HashMap();
                    parametros.put("Ano",jCAno.getSelectedItem().toString());
                    parametros.put("Grado",jCGrado.getSelectedItem().toString());
                    parametros.put("logo",this.getClass().getResourceAsStream(logotipo));
                    parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
                    InputStream file= getClass().getResourceAsStream("/Reportes_Primero/Promedio_Secundaria.jrxml");
                    JasperDesign jasperDesign= JRXmlLoader.load(file);
                    JasperReport jasperReport= JasperCompileManager.compileReport(jasperDesign);
                    JasperPrint jp =JasperFillManager.fillReport(jasperReport,parametros,cn);
                    JasperViewer ventanaVisor= new JasperViewer(jp,false);
                    ventanaVisor.setTitle("INFORME PROMEDIOS PRIMER PERÍODO");
                    ventanaVisor.setVisible(true);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            }//END IF SEXTO
            else if(jCGrado.getSelectedItem().equals("9")){

                try {
                    Map parametros=new HashMap();
                    parametros.put("Ano",jCAno.getSelectedItem().toString());
                    parametros.put("Grado",jCGrado.getSelectedItem().toString());
                    parametros.put("logo",this.getClass().getResourceAsStream(logotipo));
                    parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
                    InputStream file= getClass().getResourceAsStream("/Reportes_Primero/Promedio_Media.jrxml");
                    JasperDesign jasperDesign= JRXmlLoader.load(file);
                    JasperReport jasperReport= JasperCompileManager.compileReport(jasperDesign);
                    JasperPrint jp =JasperFillManager.fillReport(jasperReport,parametros,cn);
                    JasperViewer ventanaVisor= new JasperViewer(jp,false);
                    ventanaVisor.setTitle("INFORME PROMEDIOS PRIMER PERÍODO");
                    ventanaVisor.setVisible(true);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            }else if(jCGrado.getSelectedItem().equals("10") || jCGrado.getSelectedItem().equals("11")){

                try {
                    Map parametros=new HashMap();
                    parametros.put("Ano",jCAno.getSelectedItem().toString());
                    parametros.put("Grado",jCGrado.getSelectedItem().toString());
                    parametros.put("logo",this.getClass().getResourceAsStream(logotipo));
                    parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
                    InputStream file= getClass().getResourceAsStream("/Reportes_Primero/Promedio_Once.jrxml");
                    JasperDesign jasperDesign= JRXmlLoader.load(file);
                    JasperReport jasperReport= JasperCompileManager.compileReport(jasperDesign);
                    JasperPrint jp =JasperFillManager.fillReport(jasperReport,parametros,cn);
                    JasperViewer ventanaVisor= new JasperViewer(jp,false);
                    ventanaVisor.setTitle("INFORME PROMEDIOS PRIMER PERÍODO");
                    ventanaVisor.setVisible(true);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            }
        }
        else if(jCPeriodo.getSelectedItem().equals("SEGUNDO") ){
            if(jCGrado.getSelectedItem().equals("1") || jCGrado.getSelectedItem().equals("2") || jCGrado.getSelectedItem().equals("3") || jCGrado.getSelectedItem().equals("4") || jCGrado.getSelectedItem().equals("5") ){

                try {
                    String rutaInforme="Reportes_Segundo/Primaria.jasper";
                    Map parametros=new HashMap();
                    Map parametro=new HashMap();
                    parametros.put("Ano",jCAno.getSelectedItem().toString());
                    parametros.put("Grado",jCGrado.getSelectedItem().toString());
                    parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
                    JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
                    JasperViewer ventanaVisor= new JasperViewer(Informe,false);
                    ventanaVisor.setTitle("INFORME ACADÉMICO SEGUNDO PERIODO");
                    ventanaVisor.setVisible(true);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            }

            else if(jCGrado.getSelectedItem().equals("6") || jCGrado.getSelectedItem().equals("7") || jCGrado.getSelectedItem().equals("8")){

                try {
                    String rutaInforme="Reportes_Segundo/Secundaria.jasper";
                    Map parametros=new HashMap();
                    Map parametro=new HashMap();
                    parametros.put("Ano",jCAno.getSelectedItem().toString());
                    parametros.put("Grado",jCGrado.getSelectedItem().toString());
                    parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
                    JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
                    JasperViewer ventanaVisor= new JasperViewer(Informe,false);
                    ventanaVisor.setTitle("INFORME ACADÉMICO SEGUNDO PERIODO");
                    ventanaVisor.setVisible(true);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            }//END IF SEXTO
            else if(jCGrado.getSelectedItem().equals("9")){

                try {
                    String rutaInforme="Reportes_Segundo/Media.jasper";
                    Map parametros=new HashMap();
                    Map parametro=new HashMap();
                    parametros.put("Ano",jCAno.getSelectedItem().toString());
                    parametros.put("Grado",jCGrado.getSelectedItem().toString());
                    parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
                    JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
                    JasperViewer ventanaVisor= new JasperViewer(Informe,false);
                    ventanaVisor.setTitle("INFORME ACADÉMICO TERCER PERIODO");
                    ventanaVisor.setVisible(true);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            }else if(jCGrado.getSelectedItem().equals("10") || jCGrado.getSelectedItem().equals("11")){

                try {
                    String rutaInforme="Reportes_Segundo/Once.jasper";
                    Map parametros=new HashMap();
                    Map parametro=new HashMap();
                    parametros.put("Ano",jCAno.getSelectedItem().toString());
                    parametros.put("Grado",jCGrado.getSelectedItem().toString());
                    parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
                    JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
                    JasperViewer ventanaVisor= new JasperViewer(Informe,false);
                    ventanaVisor.setTitle("INFORME ACADÉMICO SEGUNDO PERIODO");
                    ventanaVisor.setVisible(true);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            }
        }
        /// ADRIANA 
    /////////////////////////////////////// INICIO TERCER PERÍODO////////////////////////////////
        else if(jCPeriodo.getSelectedItem().equals("TERCERO") ){
            if(jCGrado.getSelectedItem().equals("1") || jCGrado.getSelectedItem().equals("2")){

                try {
                    String rutaInforme="Reportes_Tercero/Promedio_Primaria_uno_dos.jasper";
                    Map parametros=new HashMap();
                    Map parametro=new HashMap();
                    parametros.put("Ano",jCAno.getSelectedItem().toString());
                    parametros.put("Grado",jCGrado.getSelectedItem().toString());
                    parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
                    JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
                    JasperViewer ventanaVisor= new JasperViewer(Informe,false);
                    ventanaVisor.setTitle("CONSOLIDADO DE PROMEDIOS TERCER PERIODO");
                    ventanaVisor.setVisible(true);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            } else if(jCGrado.getSelectedItem().equals("3") || jCGrado.getSelectedItem().equals("4") || jCGrado.getSelectedItem().equals("5") ){

                try {
                    String rutaInforme="Reportes_Tercero/Promedio_Primaria.jasper";
                    Map parametros=new HashMap();
                    Map parametro=new HashMap();
                    parametros.put("Ano",jCAno.getSelectedItem().toString());
                    parametros.put("Grado",jCGrado.getSelectedItem().toString());
                    parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
                    JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
                    JasperViewer ventanaVisor= new JasperViewer(Informe,false);
                    ventanaVisor.setTitle("CONSOLIDADO DE PROMEDIOS TERCER PERIODO");
                    ventanaVisor.setVisible(true);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            }

            else if(jCGrado.getSelectedItem().equals("6") || jCGrado.getSelectedItem().equals("7") || jCGrado.getSelectedItem().equals("8")){

                try {
                    String rutaInforme="Reportes_Tercero/Promedio_Secundaria.jasper";
                    Map parametros=new HashMap();
                    Map parametro=new HashMap();
                    parametros.put("Ano",jCAno.getSelectedItem().toString());
                    parametros.put("Grado",jCGrado.getSelectedItem().toString());
                    parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
                    JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
                    JasperViewer ventanaVisor= new JasperViewer(Informe,false);
                    ventanaVisor.setTitle("CONSOLIDADO DE PROMEDIOS TERCER PERIODO");
                    ventanaVisor.setVisible(true);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            }//END IF SEXTO
            else if(jCGrado.getSelectedItem().equals("9")){

                try {
                    String rutaInforme="Reportes_Tercero/Promedio_Media.jasper";
                    Map parametros=new HashMap();
                    Map parametro=new HashMap();
                    parametros.put("Ano",jCAno.getSelectedItem().toString());
                    parametros.put("Grado",jCGrado.getSelectedItem().toString());
                    parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
                    JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
                    JasperViewer ventanaVisor= new JasperViewer(Informe,false);
                    ventanaVisor.setTitle("CONSOLIDADO DE PROMEDIOS TERCER PERIODO");
                    ventanaVisor.setVisible(true);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            }else if(jCGrado.getSelectedItem().equals("10") || jCGrado.getSelectedItem().equals("11")){

                try {
                    String rutaInforme="Reportes_Tercero/Promedio_Once.jasper";
                    Map parametros=new HashMap();
                    Map parametro=new HashMap();
                    parametros.put("Ano",jCAno.getSelectedItem().toString());
                    parametros.put("Grado",jCGrado.getSelectedItem().toString());
                    parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
                    JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
                    JasperViewer ventanaVisor= new JasperViewer(Informe,false);
                    ventanaVisor.setTitle("CONSOLIDADO DE PROMEDIOS TERCER PERIODO");
                    ventanaVisor.setVisible(true);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            }
        }
  /// ADRIANA 
    /////////////////////////////////////// INICIO CUARTO PERÍODO////////////////////////////////
        else if(jCPeriodo.getSelectedItem().equals("CUARTO") ){
            if(jCGrado.getSelectedItem().equals("1") || jCGrado.getSelectedItem().equals("2")){

                try {
                    String rutaInforme="Reportes_Cuarto/Promedio_Primaria_uno_dos.jasper";
                    Map parametros=new HashMap();
                    Map parametro=new HashMap();
                    parametros.put("Ano",jCAno.getSelectedItem().toString());
                    parametros.put("Grado",jCGrado.getSelectedItem().toString());
                    parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
                    JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
                    JasperViewer ventanaVisor= new JasperViewer(Informe,false);
                    ventanaVisor.setTitle("CONSOLIDADO DE PROMEDIOS CUARTO PERIODO");
                    ventanaVisor.setVisible(true);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            } else if(jCGrado.getSelectedItem().equals("3") || jCGrado.getSelectedItem().equals("4") || jCGrado.getSelectedItem().equals("5") ){

                try {
                    String rutaInforme="Reportes_Cuarto/Promedio_Primaria.jasper";
                    Map parametros=new HashMap();
                    Map parametro=new HashMap();
                    parametros.put("Ano",jCAno.getSelectedItem().toString());
                    parametros.put("Grado",jCGrado.getSelectedItem().toString());
                    parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
                    JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
                    JasperViewer ventanaVisor= new JasperViewer(Informe,false);
                    ventanaVisor.setTitle("CONSOLIDADO DE PROMEDIOS CUARTO PERIODO");
                    ventanaVisor.setVisible(true);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            }

            else if(jCGrado.getSelectedItem().equals("6") || jCGrado.getSelectedItem().equals("7") || jCGrado.getSelectedItem().equals("8")){

                try {
                    String rutaInforme="Reportes_Cuarto/Promedio_Secundaria.jasper";
                    Map parametros=new HashMap();
                    Map parametro=new HashMap();
                    parametros.put("Ano",jCAno.getSelectedItem().toString());
                    parametros.put("Grado",jCGrado.getSelectedItem().toString());
                    parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
                    JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
                    JasperViewer ventanaVisor= new JasperViewer(Informe,false);
                    ventanaVisor.setTitle("CONSOLIDADO DE PROMEDIOS CUARTO PERIODO");
                    ventanaVisor.setVisible(true);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            }//END IF SEXTO
            else if(jCGrado.getSelectedItem().equals("9")){

                try {
                    String rutaInforme="Reportes_Cuarto/Promedio_Media.jasper";
                    Map parametros=new HashMap();
                    Map parametro=new HashMap();
                    parametros.put("Ano",jCAno.getSelectedItem().toString());
                    parametros.put("Grado",jCGrado.getSelectedItem().toString());
                    parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
                    JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
                    JasperViewer ventanaVisor= new JasperViewer(Informe,false);
                    ventanaVisor.setTitle("CONSOLIDADO DE PROMEDIOS CUARTO PERIODO");
                    ventanaVisor.setVisible(true);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            }else if(jCGrado.getSelectedItem().equals("10") || jCGrado.getSelectedItem().equals("11")){

                try {
                    String rutaInforme="Reportes_Cuarto/Promedio_Once.jasper";
                    Map parametros=new HashMap();
                    Map parametro=new HashMap();
                    parametros.put("Ano",jCAno.getSelectedItem().toString());
                    parametros.put("Grado",jCGrado.getSelectedItem().toString());
                    parametros.put("Periodo",jCPeriodo.getSelectedItem().toString());
                    JasperPrint Informe= JasperFillManager.fillReport(rutaInforme,parametros,cn);
                    JasperViewer ventanaVisor= new JasperViewer(Informe,false);
                    ventanaVisor.setTitle("CONSOLIDADO DE PROMEDIOS CUARTO PERIODO");
                    ventanaVisor.setVisible(true);
                }
                catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"ERROR EN EL REPORTE","ERROR",JOptionPane.ERROR_MESSAGE);

                }
            }
        }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jCAno;
    private javax.swing.JComboBox<String> jCGrado;
    private javax.swing.JComboBox<String> jCPeriodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    // End of variables declaration//GEN-END:variables
}
